language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
script: "./gradlew check"
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: mgoel@andrew.cmu.edu
  password:
    secure: yD/CAe9OWvNa8ht1gi+xEQKr3AEQRIrPmTXHcg3e7Cwd6P0iGxaxm2u/xk+0atRICps2Lp/fTPpwJRVgIz+pTJvx5kKs7UdGjRI+dhHP6D0mP2L6wwMK5mRrbSrkgX7TBZ7O9k8gFeozV71iNVX4Ch8FEg2XrKNlTye2uXuwHze++e3nY3iAHwkw/z+qKSoUMoBwMdKr44/4FAHBtttrBY/kqmIjw2lxlA9qQw4XFB/H8fvgyNSwkce6F3GJMqjPIxs1NRnFzwHYf1MHSivl8bdXLff4viLD1DbQJn1kdhGXW9G3wJ6VXOhFxICWlRn+iKLQei1mB1MfrOijDtc6JLrdeKgcOyhi59+L7Yc8PK/17zL16b8QV+NURacvWngc69K3UES4MGW2DNarXPrSPq0iZueQvDLdJ6vFUD/4WDA0c2YxF7wDtEM671cMJkag0PQAIFYQwnCNPWrJ/2NZXHPu9zlXJibgScdP9cKOacFj5yXdjuTa2X80WVxDoolGrFPdTqMkpP+G/iv40xmJa//Q+j0DG0qEBkFXZwgnXtR2QmcMN5U2jZ5cjVaNFPH1s70Rk5Ba6R5pHlhKMSV8/aXW9EXv/K0Rcf+ZfYiNU5rITtimloW2xfcdO6lSUui62rkUyxoNz3r5PYCFcAE09lN8NiHYJgntyBjUhw1qpoQ=
  organization: mgoel-cmu
  space: development
  on:
    repo: muditgoel/Image-Gallery-Application
